### ISSUE TITLE
有的美剧好像查询不到信息

### ISSUE THREAD

**Issue by yangxuan8282** [SudaVideo/MyVideoApi#2]
比如 太空无垠-第3季 ，用 curl 请求 `/video/detail?source=3&videoId=teleplay+list08+5311.html` 这个地址返回的是：

```
{"data":{"videoSeries":[],"desc":"","previewImgs":[]},"success":true}
```

这个是因为格式的问题吗还是其它

**Comment by ghbhaha** [comment]
url做下转码

**Comment by yangxuan8282** [comment]
@ghbhaha 能给个例子吗，比如上面那个 url 该怎么转

**Comment by ghbhaha** [comment]
video/detail?source=3&videoId=teleplay%2blist08%2b5311.html
使用http://tool.chinaz.com/tools/urlencode.aspx

**Comment by yangxuan8282** [comment]
@ghbhaha 好的，谢谢了

**Comment by yangxuan8282** [comment]
今天好像解析不到播放地址了

**Comment by ghbhaha** [comment]
哪个

**Comment by yangxuan8282** [comment]
刚才好像是我网络的问题，试了几个视频没返回地址
问下想加资源网站的话有什么要求吗，比如播放页面的 url 是要类似 /video/%s?Play=%s 这种，还是别的也行，比如这个站 http://www.kanbo8.com/

**Comment by ghbhaha** [comment]
没有要求，子类实现
https://github.com/SudaVideo/MyVideoApi/blob/5166dc19733e684eabd5f54ea7cfa3db17d44d48/src/main/java/com/suda/MyVideoApi/service/BaseVideoService.java中的几个protected方法

**Comment by yangxuan8282** [comment]
不知道楼主研究过它们这些站的资源是怎么来的没有

这两天看了一下类似的视频站发现，它们电影资源站主要存放在：

- 百度，vd3.bdstatic.com，通过好看视频上传

- 天翼云，gz189cloud2.oos-gz.ctyunapi.cn，( 通过 api 获取地址？)

- 腾讯微云，*.myqcloud.com，( api获取播放地址？)

后两个那种不知道是直接上传的还是类似 A, B 站以前那种传到别的服务上 ( 记得当时有些视频是在乐视云上 ) 然后解析到的地址，现在的 D 站应该还是这种

上面这几个地址的下载速度很快，基本随意拖拽，不过看了一些同类的站发现资源不是很丰富，新资源好说，老一点的美剧就找不到了

还有一些其它类型的

- *.438vip.com ( 目前发现有 v1, v2 两个前缀， 在网页源代码中可以找到 m3u8，手机上打开可以直接播放 )

- ckm3u8 ( 在部分采集站可以找到 m3u8 结果，比如 www.okzy.me , www.131zy.net 这种 )

- kuyun

后面这几个速度慢不少，不过也能基本流畅，而且这种资源多，很多老资源也能找到，而且不像上面那种直接获取播放地址的会很快过期 ( 大概两三个小时的样子 )，所以不需要太频繁抓取

其实以 "m3u8 资源站" 进行搜索能搜到不少资源站，比如这个[博客](http://www.tttxx.cn/index.php/four/4/) 列了几个，这些站用的采集好像也都是开放下载的，直接提供 api

不知道比如 91mjw.com 这些上传到百度好看视频和天翼云的资源站也是用的现成的 api 还是自己手动搞的，估计是现成的 api 可能性大一些，如果能找到这种 api 的话会方便很多

edit: 看了下 sudavideo.site 采集的那几个站，发现它们都用的这个： api.1suplayer.me
